#ifndef XSAN_ERROR_H
#define XSAN_ERROR_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef int32_t xsan_error_t;

/* Generic Errors */
#define XSAN_OK 0
#define XSAN_ERROR_GENERIC -1
#define XSAN_ERROR_SYSTEM -2
#define XSAN_ERROR_INVALID_PARAM -3
#define XSAN_ERROR_NOT_INITIALIZED -4
#define XSAN_ERROR_THREAD_CONTEXT -5
#define XSAN_ERROR_NETWORK -6
#define XSAN_ERROR_TIMEOUT -7
#define XSAN_ERROR_PERMISSION_DENIED -8
#define XSAN_ERROR_NOT_FOUND -9
#define XSAN_ERROR_ALREADY_EXISTS -10
#define XSAN_ERROR_BUSY -11
#define XSAN_ERROR_NO_MEMORY -12
#define XSAN_ERROR_UNSUPPORTED -13
#define XSAN_ERROR_IO -14
#define XSAN_ERROR_INTERRUPTED -15
#define XSAN_ERROR_CANCELED -16
#define XSAN_ERROR_RESOURCE_EXHAUSTED -17
#define XSAN_ERROR_INVALID_STATE -18

/* Cluster Errors */
#define XSAN_ERROR_CLUSTER_GENERIC -20
#define XSAN_ERROR_NODE_NOT_FOUND -21
#define XSAN_ERROR_NODE_UNREACHABLE -22
#define XSAN_ERROR_NODE_FAILED -23
#define XSAN_ERROR_NODE_EXISTS -24
#define XSAN_ERROR_INVALID_NODE_STATE -25

/* Storage & Device Errors */
#define XSAN_ERROR_STORAGE_GENERIC -80
#define XSAN_ERROR_DEVICE_FAILED -81
#define XSAN_ERROR_DEVICE_NOT_FOUND -82
#define XSAN_ERROR_VOLUME_NOT_FOUND -83
#define XSAN_ERROR_VOLUME_EXISTS -84
#define XSAN_ERROR_VOLUME_BUSY -85
#define XSAN_ERROR_BLOCK_NOT_FOUND -86
#define XSAN_ERROR_BLOCK_CORRUPTED -87

/* Replication Errors */
#define XSAN_ERROR_REPLICATION_GENERIC -100
#define XSAN_ERROR_REPLICA_NOT_FOUND -101
#define XSAN_ERROR_REPLICA_OUTDATED -102
#define XSAN_ERROR_SYNC_FAILED -103
#define XSAN_ERROR_CONSISTENCY_CHECK_FAILED -104
#define XSAN_ERROR_RECOVERY_FAILED -105
#define XSAN_ERROR_NOT_ENOUGH_REPLICAS -106

/* Policy Errors */
#define XSAN_ERROR_POLICY_GENERIC -120
#define XSAN_ERROR_POLICY_NOT_FOUND -121
#define XSAN_ERROR_POLICY_VIOLATION -122
#define XSAN_ERROR_QOS_LIMIT_EXCEEDED -123

/* Virtualization Errors */
#define XSAN_ERROR_VIRTUALIZATION_GENERIC -140
#define XSAN_ERROR_LIBVIRT_FAILED -141
#define XSAN_ERROR_VM_NOT_FOUND -142
#define XSAN_ERROR_STORAGE_POOL_FAILED -143

/* Configuration Errors */
#define XSAN_ERROR_CONFIG_GENERIC -160
#define XSAN_ERROR_CONFIG_INVALID -161
#define XSAN_ERROR_CONFIG_MISSING -162
#define XSAN_ERROR_CONFIG_PARSE -163

/* Metadata Errors */
#define XSAN_ERROR_METADATA_GENERIC -180
#define XSAN_ERROR_METADATA_READ_FAILED -181
#define XSAN_ERROR_METADATA_WRITE_FAILED -182
#define XSAN_ERROR_METADATA_CORRUPTED -183

/* Task/Job Errors */
#define XSAN_ERROR_TASK_GENERIC -200
#define XSAN_ERROR_TASK_NOT_FOUND -201
#define XSAN_ERROR_TASK_FAILED -202
#define XSAN_ERROR_TASK_CANCELLED -203

/* Security Errors */
#define XSAN_ERROR_SECURITY_GENERIC -220
#define XSAN_ERROR_AUTHENTICATION_FAILED -221
#define XSAN_ERROR_AUTHORIZATION_FAILED -222
#define XSAN_ERROR_ENCRYPTION_FAILED -223
#define XSAN_ERROR_DECRYPTION_FAILED -224

#ifdef __cplusplus
}
#endif

#endif // XSAN_ERROR_H
