
#ifndef XSAN_ERROR_H
#define XSAN_ERROR_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef int32_t xsan_error_t;

// 通用错误码
#define XSAN_OK 0
#define XSAN_ERROR_GENERIC -1
#define XSAN_ERROR_INVALID_PARAM -2
#define XSAN_ERROR_BUSY -3
#define XSAN_ERROR_NOT_FOUND -4
#define XSAN_ERROR_ALREADY_EXISTS -5
#define XSAN_ERROR_TIMEOUT -6
#define XSAN_ERROR_NO_MEMORY -7
#define XSAN_ERROR_IO -8
#define XSAN_ERROR_PERMISSION_DENIED -9
#define XSAN_ERROR_INTERRUPTED -10
#define XSAN_ERROR_SYSTEM -11
#define XSAN_ERROR_UNSUPPORTED -12
#define XSAN_ERROR_NOT_INITIALIZED -13
#define XSAN_ERROR_THREAD_CONTEXT -14

// 网络相关
#define XSAN_ERROR_NETWORK -20
#define XSAN_ERROR_NODE_UNREACHABLE -21
#define XSAN_ERROR_CONNECTION_LOST -22
#define XSAN_ERROR_CONNECTION_REFUSED -23
#define XSAN_ERROR_ADDRESS_IN_USE -24
#define XSAN_ERROR_NETWORK_DOWN -25
#define XSAN_ERROR_HOST_UNREACHABLE -26

// 存储相关
#define XSAN_ERROR_STORAGE_GENERIC -40
#define XSAN_ERROR_DEVICE_FAILED -41
#define XSAN_ERROR_DEVICE_NOT_FOUND -42
#define XSAN_ERROR_VOLUME_NOT_FOUND -43
#define XSAN_ERROR_VOLUME_EXISTS -44
#define XSAN_ERROR_VOLUME_BUSY -45
#define XSAN_ERROR_BLOCK_NOT_FOUND -46
#define XSAN_ERROR_BLOCK_CORRUPTED -47
#define XSAN_ERROR_DISK_FULL -48
#define XSAN_ERROR_INSUFFICIENT_SPACE -49
#define XSAN_ERROR_STORAGE_IO -50

// 集群相关
#define XSAN_ERROR_CLUSTER_GENERIC -60
#define XSAN_ERROR_NODE_NOT_FOUND -61
#define XSAN_ERROR_NODE_EXISTS -62
#define XSAN_ERROR_SPLIT_BRAIN -63
#define XSAN_ERROR_QUORUM_LOST -64
#define XSAN_ERROR_CLUSTER_NOT_READY -65
#define XSAN_ERROR_INVALID_NODE_STATE -66

// 复制相关
#define XSAN_ERROR_REPLICATION_GENERIC -80
#define XSAN_ERROR_REPLICA_NOT_FOUND -81
#define XSAN_ERROR_REPLICA_OUTDATED -82
#define XSAN_ERROR_SYNC_FAILED -83
#define XSAN_ERROR_CONSISTENCY_CHECK_FAILED -84
#define XSAN_ERROR_RECOVERY_FAILED -85
#define XSAN_ERROR_NOT_ENOUGH_REPLICAS -86

// 策略相关
#define XSAN_ERROR_POLICY_GENERIC -100
#define XSAN_ERROR_POLICY_NOT_FOUND -101
#define XSAN_ERROR_POLICY_VIOLATION -102
#define XSAN_ERROR_QOS_LIMIT_EXCEEDED -103

// 虚拟化相关
#define XSAN_ERROR_VIRTUALIZATION_GENERIC -120
#define XSAN_ERROR_LIBVIRT_FAILED -121
#define XSAN_ERROR_VM_NOT_FOUND -122
#define XSAN_ERROR_STORAGE_POOL_FAILED -123

// 配置相关
#define XSAN_ERROR_CONFIG_GENERIC -140
#define XSAN_ERROR_CONFIG_INVALID -141
#define XSAN_ERROR_CONFIG_MISSING -142
#define XSAN_ERROR_CONFIG_PARSE -143

// 元数据相关
#define XSAN_ERROR_METADATA_GENERIC -160
#define XSAN_ERROR_METADATA_READ_FAILED -161
#define XSAN_ERROR_METADATA_WRITE_FAILED -162
#define XSAN_ERROR_METADATA_CORRUPTED -163

// 任务相关
#define XSAN_ERROR_TASK_GENERIC -180
#define XSAN_ERROR_TASK_NOT_FOUND -181
#define XSAN_ERROR_TASK_FAILED -182
#define XSAN_ERROR_TASK_CANCELLED -183

// 安全相关
#define XSAN_ERROR_SECURITY_GENERIC -200
#define XSAN_ERROR_AUTHENTICATION_FAILED -201
#define XSAN_ERROR_AUTHORIZATION_FAILED -202
#define XSAN_ERROR_ENCRYPTION_FAILED -203
#define XSAN_ERROR_DECRYPTION_FAILED -204

#ifdef __cplusplus
}
#endif

#endif // XSAN_ERROR_H
